# -- 코드를 입력하세요
SELECT prod.PRODUCT_ID, PRODUCT_NAME, SUM(AMOUNT) * PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT prod JOIN FOOD_ORDER ord ON prod.product_id = ord.product_id
WHERE DATE_FORMAT(ord.PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC